[package]
name = "vr_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vr_lib = { path = "../vanilla_rest_lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"